#lang racket

;List of numbers used in Countdown Game
(define numList (list 1 1 2 2 3 3 4 4 5 5 6 6 7 7 8 8 9 9 10 10 25 50 75 100))

;Generate Random Number between 101 and 999
;define rand function, call the "random" library function, give it range min max.
(define tarNum
  (random 101 1000))

;working on thread to work while waiting for results...
;(thread (lambda () (let loop () (display ".") (sleep 1.0) (loop))))

;Select random element from a list.
;Get the length of our list, using "random" library function get the random element from the list.
;Using "list-ref" library function we return element from list of numbers "list" at a position generated by "random" function.
; https://docs.racket-lang.org/guide/set_.html
; If the length of "randSix" list is = 6 set it to randSIx, else repeat process.
(define randSix(list))
(define (rand-element list)
  (define randomNumber (list-ref list (random (length list))))
     (set! randSix(cons randomNumber randSix))
     (set! list (remq randomNumber list))
  (if(= 6(length randSix))
     randSix
     (rand-element list))
  )
(quasiquote (Six Random Numbers: (unquote (rand-element numList)) & Target Number: (unquote tarNum)))
(quasiquote (Processing... Please Wait))

;l holds the permutations of randSix
(define l (permutations randSix))

;Generating 5 operators from a list of 4 using cartesian-product
(define ops '(+ - / *))
(define all-ops(cartesian-product ops ops ops ops ops))

;counter to check if it's going accordingly to calculation
(define equationCount 0)

(define ns (make-base-namespace))

;Acculumator lists: accuList + equationList
(define accuList null)
(define equationList null)

;Below i'm defining an equation in format of:
; (+ (/ (* (- (+ 1 2) 3) 4) 5) 6)

;aList + tNum in both equation + opseq are both accumulator lists (local to function)
;outer function - used to start program
;checks if permList is null, if it is throws a 0 else it calls opseq function and feeds it with necessary data required in the opseq function and calls
;itself on next (cdr) list of permutates numbers (permList)
(define (equation permList operators aList tNum)
 (if (null? permList)
     0
     (begin 
      (opseq operators permList aList tNum)
      (equation (cdr permList) operators aList tNum)
      )
  )
)

;inner function - defining the format of the equation and adding "correct" equation to list
;correct equation means if the result of it equals the target number.
;opseq takes in operators, number permutations list and 2 accumulator lists
;checks if all-ops list is empty and if it isn't it begins to do up the equation with data provided from the equation function
;equationCount simply shows how many times it happens
;quasiquote is to make the equation and unquote within quasiquote is to actually treat it as not a comment.
;then it evaluates if the equationList is equal to target number and if it is it adds it to a accuList that holds all equations that equal target number
;else it repeats process with next list of operators.
(define (opseq all-ops permList aList tNum)
 (if (null? all-ops)
    0
    (begin
      (set! equationCount (+ 1 equationCount))
      (set! equationList (quasiquote
             ((unquote(list-ref(list-ref all-ops 0)4))
              ((unquote(list-ref(list-ref all-ops 0)3))
               ((unquote(list-ref(list-ref all-ops 0)2))
                ((unquote(list-ref(list-ref all-ops 0)1))
                 ((unquote(list-ref(list-ref all-ops 0)0))
                  (unquote(list-ref (list-ref permList 0) 0))
                  (unquote(list-ref (list-ref permList 0) 1)))
                 (unquote(list-ref (list-ref permList 0) 2)))
                (unquote(list-ref (list-ref permList 0) 3)))
               (unquote(list-ref (list-ref permList 0) 4)))
              (unquote(list-ref (list-ref permList 0) 5)))
             ))
      (if (= (eval equationList ns) tNum)
          (opseq (cdr all-ops) permList (set! accuList (cons equationList accuList)) tNum)
          (opseq (cdr all-ops) permList aList tNum)))))

;running the program + all data display
(time(equation l all-ops accuList tarNum))
;displays used list of numbers and target Number
(quasiquote (All possible equations using: (unquote randSix) for Target Number: (unquote tarNum)))
;displays all equations that equal target number
accuList
;shows total equations program went through
(quasiquote (Used: Brute-Force: Total Tested Equations: (unquote equationCount)))
;shows how many equations equal target number in count format + shows the target number
(quasiquote (There are: (unquote (length accuList)) different possible equations for Target Number:(unquote tarNum) - Process Complete.))
